Parameters:
  QueuedBucketName:
    Type: String
    Default: 'patterns-s3docrepo-queued'


Resources:
  QueuedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref QueuedBucketName

  MyAddToESFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: MyAddToESFunctionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                  - 's3:GetObjectVersion'
                  - 's3:GetLifecycleConfiguration'
                Resource:
                  - !GetAtt
                    - QueuedBucket
                    - Arn
                  - !Join 
                    - ''
                    - - !GetAtt 
                        - QueuedBucket
                        - Arn
                      - /*
                Effect: Allow
              - Action:
                  - 'comprehend:*'
                Resource:
                  - '*'
                Effect: Allow

  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: 'department-doc'
      ClusterConfig:
        InstanceCount: '1'
        InstanceType: 't2.small.search'

      EBSOptions:
        EBSEnabled: true
        Iops: '0'
        VolumeSize: '20'
        VolumeType: 'gp2'

      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS:
                - !GetAtt MyAddToESFunctionRole.Arn
                - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/department-doc/*'


Outputs: 
  OpenSearchEndpoint:
    Description: The Endpoint for OpenSearch
    Value:
      Fn::GetAtt:
      - OpenSearchServiceDomain
      - DomainEndpoint

  MyAddToESFunctionRole:
    Description: The Arn for MyAddToESFunctionRole
    Value:
      Fn::GetAtt:
      - MyAddToESFunctionRole
      - Arn