Parameters:
  KendraBucketName:
    Type: String
    Default: kendra-documents
Resources:
  KendraIndexRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: KendraIndexRoleforS3
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'cloudwatch:PutMetricData'
                Resource: '*'
                Condition:
                  StringEquals:
                    'cloudwatch:namespace': Kendra
              - Effect: Allow
                Action: 'logs:DescribeLogGroups'
                Resource: '*'
              - Effect: Allow
                Action: 'logs:CreateLogGroup'
                Resource: !Sub >-
                  arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kendra/*
              - Effect: Allow
                Action:
                  - 'logs:DescribeLogStreams'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub >-
                  arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kendra/*:log-stream:*
  KendraDataSourceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: KendraDataSourceRoleforS3
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource:
                  - !Join 
                    - ''
                    - - !GetAtt 
                        - KendraBucket
                        - Arn
                      - /*
                Effect: Allow
              - Action:
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt 
                    - KendraBucket
                    - Arn
                Effect: Allow
              - Effect: Allow
                Action:
                  - 'kendra:BatchPutDocument'
                  - 'kendra:BatchDeleteDocument'
                Resource:
                  - !Sub 
                    - >-
                      arn:aws:kendra:${AWS::Region}:${AWS::AccountId}:index/{index}
                    - index: !Ref KendraIndex
  KendraBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref KendraBucketName
  KendraIndex:
    Type: 'AWS::Kendra::Index'
    Properties:
      Edition: DEVELOPER_EDITION
      Name: GroupDocumentKendraIndex
      RoleArn: !GetAtt 
        - KendraIndexRole
        - Arn
  KendraDataSource:
    Type: 'AWS::Kendra::DataSource'
    Properties:
      DataSourceConfiguration:
        S3Configuration:
          BucketName: !Ref KendraBucket
      IndexId: !Ref KendraIndex
      Name: GroupDocumentKendraDataSource
      RoleArn: !GetAtt 
        - KendraDataSourceRole
        - Arn
      Type: S3
